# Generated by Django 5.0.6 on 2024-06-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='news_pictures/'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
