# Generated by Django 5.0.6 on 2024-06-03 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0002_alter_news_pictures_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tags',
        ),
    ]
