# Generated by Django 5.0.6 on 2024-06-03 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0004_news_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='pictures',
            new_name='picture',
        ),
    ]
